<?php

namespace DBSeed;

class SampleUser {

    /**
     * SampleUser constructor.
     */
    public function __construct() { }

    public static function allUserInRedmine() {
        return [
            ['id' => 163, 'name' => 'Chi Mac Cong [PG]'],
            ['id' => 16, 'name' => 'Don Nguyen Van [PG]'],
            ['id' => 61, 'name' => 'ENDO Yusuke'],
            ['id' => 250, 'name' => 'Hai Pham Thanh [Manager]'],
            ['id' => 115, 'name' => 'Kanada Kentaro'],
            ['id' => 3, 'name' => 'KAWAHARA Kazuyasu'],
            ['id' => 137, 'name' => 'Luan Pham Ngoc [PG]'],
            ['id' => 98, 'name' => 'Son Vi Hoang [PG]'],
            ['id' => 65, 'name' => 'Tien Huynh Cong [PG]'],
            ['id' => 14, 'name' => 'Cong Vo Chi [PG]  '],
            ['id' => 101, 'name' => 'Cuong Nguyen Tran Quoc  [PG]'],
            ['id' => 48, 'name' => 'Duc Nguyen Quang [PG]'],
            ['id' => 134, 'name' => 'Hung Nguyen Duc [PG]'],
            ['id' => 195, 'name' => 'Hoan Nguyen Minh [QC]'],
            ['id' => 170, 'name' => 'Bi Ho Sy Ly [PG]'],
            ['id' => 138, 'name' => 'Hoa Nguyen Duc  [ITC]'],
            ['id' => 173, 'name' => 'Hoai Nguyen Van [PG]'],
            ['id' => 151, 'name' => 'Huy Le Anh [PG]'],
            ['id' => 225, 'name' => 'Khanh Ha Quoc [PG]'],
            ['id' => 153, 'name' => 'Le Le Gia [PG]'],
            ['id' => 165, 'name' => 'Le Van Linh [PG]'],
            ['id' => 78, 'name' => 'Nhat  Ho Thong [PG]'],
            ['id' => 168, 'name' => 'Nho Le Trong [PG]'],
            ['id' => 184, 'name' => 'Son Nguyen Phuoc [PG]'],
            ['id' => 70, 'name' => 'Tham Nguyen Nhu [PG]'],
            ['id' => 167, 'name' => 'Thinh Dang Luu Quoc [PG]'],
            ['id' => 215, 'name' => 'Trang Tran Thi Nha [ITC]'],
            ['id' => 108, 'name' => 'Truong Nguyen Nhat [PG]'],
            ['id' => 200, 'name' => 'Vu Nguyen Tuan [PG]'],
            ['id' => 214, 'name' => 'Vuong Phan Quoc [PG]'],
            ['id' => 126, 'name' => 'Quyen Nguyen Thi [ITC]'],
            ['id' => 71, 'name' => 'Quyen Tran Thi Le [QC]'],
            ['id' => 176, 'name' => 'Van Vo Thi Huynh [QC]'],
            ['id' => 1, 'name' => 'Admin Redmine'],
            ['id' => 278, 'name' => 'Anh Hoang Van Viet [PG]'],
            ['id' => 244, 'name' => 'Anh Phan Tien [PG]'],
            ['id' => 231, 'name' => 'Anh Vu Thi'],
            ['id' => 218, 'name' => 'Bui Bang [Trainer]'],
            ['id' => 288, 'name' => 'Cat Ngo Phuong [Internship]　'],
            ['id' => 96, 'name' => 'Chau Cu Thi [QC]'],
            ['id' => 93, 'name' => 'Chau Nguyen Ha Ngoc [Admin]'],
            ['id' => 245, 'name' => 'Cong Nguyen Chi [QC]'],
            ['id' => 216, 'name' => 'Cuong Nguyen Phu [QC]'],
            ['id' => 248, 'name' => 'Dao Dung'],
            ['id' => 262, 'name' => 'Dao Pham Viet [PG]'],
            ['id' => 128, 'name' => 'Dat Nguyen Tien [PG]'],
            ['id' => 258, 'name' => 'Dinh Dinh'],
            ['id' => 282, 'name' => 'Dong Tran Dinh [Internship]'],
            ['id' => 161, 'name' => 'Duong Kieu Trong [PG]'],
            ['id' => 58, 'name' => 'Goto Shohei'],
            ['id' => 180, 'name' => 'HANAGAKI Gou'],
            ['id' => 139, 'name' => 'Hieu Vo Van [PG]'],
            ['id' => 26, 'name' => 'hiroyuki hirano'],
            ['id' => 260, 'name' => 'Hoang Pham Nguyen Nhat [PG]'],
            ['id' => 274, 'name' => 'Hung Bui Cong [ITC]'],
            ['id' => 199, 'name' => 'Hung Hoang Sy [PG]'],
            ['id' => 10, 'name' => 'Huy Lam Quoc [PG]'],
            ['id' => 147, 'name' => 'Huy Tran Quang [PG]'],
            ['id' => 90, 'name' => 'Huỳnh Tuấn Vũ'],
            ['id' => 264, 'name' => 'ISHIGURO Yoshiki'],
            ['id' => 42, 'name' => 'Karasawa Hideaki'],
            ['id' => 125, 'name' => 'Kazumi TSUTSUI'],
            ['id' => 172, 'name' => 'Khang Nguyen Hoang Vinh [PG]'],
            ['id' => 284, 'name' => 'Khanh Pham [QC]'],
            ['id' => 280, 'name' => 'Khoa Mai Dang [Internship]'],
            ['id' => 57, 'name' => 'KIM Chang soo'],
            ['id' => 269, 'name' => 'KUROSAWA AYUMI'],
            ['id' => 88, 'name' => 'Lac Vong Cu [PG]'],
            ['id' => 281, 'name' => 'Lan Nguyen Thi My [Internship]'],
            ['id' => 256, 'name' => 'Linh Le Viet [PG]'],
            ['id' => 243, 'name' => 'Loi Tran Thi [ITC]'],
            ['id' => 271, 'name' => 'MARUYAMA Wataru'],
            ['id' => 246, 'name' => 'Mimura Yoko'],
            ['id' => 287, 'name' => 'Minh Tran Le Hong [Internship]'],
            ['id' => 187, 'name' => 'Minh Vong Chieng [PG]'],
            ['id' => 270, 'name' => 'NABEYAMA Wataru'],
            ['id' => 25, 'name' => 'NAKAGAKI keiji'],
            ['id' => 289, 'name' => 'NAKATANI Chiharu'],
            ['id' => 279, 'name' => 'Nga Vo Thi Hong[QC]'],
            ['id' => 82, 'name' => 'Ngan Tran Thi Kim [QC]'],
            ['id' => 227, 'name' => 'Nghiep Le Xuan [QC]'],
            ['id' => 249, 'name' => 'Ngoc Nguyen Thi Cam [Admin]'],
            ['id' => 290, 'name' => 'Nguyen Ngoc Van Anh'],
            ['id' => 272, 'name' => 'Nguyet Nguyen Thi Thanh [ITC]'],
            ['id' => 212, 'name' => 'Nhat Duong Truong [PG]'],
            ['id' => 257, 'name' => 'Nhat Le Hong [QC]'],
            ['id' => 219, 'name' => 'Nhuan Phan Thanh [Trainer]'],
            ['id' => 285, 'name' => 'Nhut Nguyen Minh [Internship]'],
            ['id' => 89, 'name' => 'Nhut Tran Minh [PG]'],
            ['id' => 46, 'name' => 'norio takei'],
            ['id' => 205, 'name' => 'Oanh  Hoang Thi Diem [QC]'],
            ['id' => 183, 'name' => 'OBI Nobuo [JPSE]'],
            ['id' => 179, 'name' => 'Pho Dang Thi Hoang [ITC]'],
            ['id' => 169, 'name' => 'Phong Vo Manh [PG]'],
            ['id' => 247, 'name' => 'Phu Ho Phong [QC] '],
            ['id' => 210, 'name' => 'Quang Nguyen Tri [PG]'],
            ['id' => 191, 'name' => 'Quy Truong Van [PG]'],
            ['id' => 234, 'name' => 'Quyen Bui Tin [PG]'],
            ['id' => 45, 'name' => 'SAITO Tadashi'],
            ['id' => 114, 'name' => 'tai thanh thuy [JPSE]'],
            ['id' => 266, 'name' => 'Takuya MATSUYOSHI'],
            ['id' => 222, 'name' => 'Thang Tran Hoang [PG]'],
            ['id' => 132, 'name' => 'Thanh  Nhien'],
            ['id' => 254, 'name' => 'Thao Phan Thi Thanh [ITC]'],
            ['id' => 157, 'name' => 'Thao Tran Minh [PG]'],
            ['id' => 202, 'name' => 'Thien Nguyen Hoang [PG]'],
            ['id' => 66, 'name' => 'Thu Ha Nguyen Anh [ITC]'],
            ['id' => 220, 'name' => 'Thu Tran Thi Ngoc [QC]'],
            ['id' => 255, 'name' => 'TOMODA Mikio'],
            ['id' => 265, 'name' => 'Tram Cao Ngoc [ADMIN]'],
            ['id' => 261, 'name' => 'Tran Thi Ngoc Bich'],
            ['id' => 275, 'name' => 'Tran Thi Ngoc Bich'],
            ['id' => 263, 'name' => 'Trang Luong Thi Huyen [QC]'],
            ['id' => 50, 'name' => 'Truc  Nguyen Thi Thanh [BSE]'],
            ['id' => 158, 'name' => 'Trung Diep Bao [PG]'],
            ['id' => 251, 'name' => 'Tuan Huynh Minh [ITC]'],
            ['id' => 135, 'name' => 'Tuan Le Ngoc [PG]'],
            ['id' => 213, 'name' => 'Tuan  Nguyen Thanh [PG]'],
            ['id' => 177, 'name' => 'Tuan Vu Anh [PG]'],
            ['id' => 229, 'name' => 'Tung Dinh Xuan [BA]'],
            ['id' => 228, 'name' => 'Van Truong Hong [MGA] '],
            ['id' => 193, 'name' => 'Vi Le Thi Tuong [BA]'],
            ['id' => 267, 'name' => 'Vinh Nguyen [PG]'],
            ['id' => 9, 'name' => 'Vu Thi Thuy'],
            ['id' => 283, 'name' => 'YAJIMA Hitomi'],
            ['id' => 59, 'name' => 'Yoshida Jun'],
            ['id' => 5, 'name' => 'Admin'],
            ['id' => 6, 'name' => 'Developer'],
            ['id' => 8, 'name' => 'Tester]'],
        ];
    }
}
